VAE:
# -------- Define the VAE model
  latent_dim: 48
  hidden_dim: 1280
  input_dim: 96  # Example for MNIST, adjust as needed
# --------- Define the experiment ---------
  batch_size: 2131
  lr: 0.0005
  weight_decay: 0.001
  num_epochs: 1000001


Diffusion:
  T: 100 # Number of training iterations
  num_epochs: 1000001
  lr: 0.0005
  batch_size: 2131
  weight_decay: 0.001
  input_dim: 96
  hidden_dim: 700
  output_dim: 96

WGAN_GP:  
  batch_size: 2131
  noise_dim: 48
  output_shape: 96
  hidden_dim: 700
  lr: 0.0002
  beta1: 0.5
  epochs: 1000001
