AUS_cgan:
  batch_size: 64
  noise_dim: 12
  condition_dim: 2
  output_shape: 48
  hidden_dim: 128
  lr: 0.0002
  beta1: 0.5
  epochs: 1000

NL_cgan:
  batch_size: 256
  noise_dim: 12
  condition_dim: 2
  output_shape: 24
  hidden_dim: 68
  lr: 0.0002
  beta1: 0.5
  epochs: 1000


UK_cgan:
  batch_size: 256
  noise_dim: 12
  condition_dim: 2
  output_shape: 48
  hidden_dim: 128
  lr: 0.0002
  beta1: 0.5
  epochs: 1000


USA_cgan:
  batch_size: 256
  noise_dim: 12
  condition_dim: 2
  output_shape: 96
  hidden_dim: 256
  lr: 0.0002
  beta1: 0.5
  epochs: 1000



UKW_cgan:
  batch_size: 256
  noise_dim: 12
  condition_dim: 9
  output_shape: 48
  hidden_dim: 128
  lr: 0.0002
  beta1: 0.5
  epochs: 1000
