FCPflow:
  #--------Define the model--------
  num_blocks: 4
  sfactor: 0.3
  hidden_dim: 128
  num_channels: 96 # resolution of the time series 
  condition_dim: 1 # unconditioned generation

  #--------Define the training--------
  lr_min: 0.0005
  lr_max: 0.001
  lr_step_size: 100
  w_decay: 0.0
  batch_size: 2131

