FCPflow:
  #--------Define the model--------
  num_blocks: 5
  sfactor: 0.7
  hidden_dim: 256
  num_channels: 48 # resolution of the time series 
  condition_dim: 3 # unconditioned generation

  #--------Define the training--------  
  lr_min: 0.000001
  lr_max: 0.001
  lr_step_size: 200
  w_decay: 0.0
  batch_size: 2000

